
# cargo-vet audits file

[[audits.anyhow]]
who = "Jan Fooken <jan@faulty.computer>"
criteria = "safe-to-deploy"
delta = "1.0.95 -> 1.0.87"
notes = "Mostly refactoring, because some APIs are now stable"

[[audits.cc]]
who = "Jan Fooken <jan@faulty.computer>"
criteria = "safe-to-deploy"
delta = "1.1.6 -> 1.1.18"

[[audits.lexopt]]
who = "Jan Fooken <jan@faulty.computer>"
criteria = "safe-to-deploy"
version = "0.3.0"
notes = """
The code looks sound and has no \"unsafe\" code blocks. It does not pull in
any dependencies
"""

[[audits.memmap2]]
who = "Jan Fooken <jan@faulty.computer>"
criteria = "safe-to-deploy"
version = "0.9.4"
notes = """
I made a non-thorough audit, which means I didn't check the soundness of the
unsafe code.  However, Mozilla did audit this code previously and I didn't
find anything concerning except from <10 lines of assembly in a test case.
"""

[[audits.pkg-config]]
who = "Jan Fooken <jan@faulty.computer>"
criteria = "safe-to-deploy"
delta = "0.3.29 -> 0.3.30"
notes = """
Updates CI workflow versions, moves the Rust installer from actions-rs to
dtolnay and does documentation changes
"""

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2026-04-27"

[[trusted.bstr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-02"
end = "2026-04-27"

[[trusted.encoding_rs_io]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-03"
end = "2026-04-27"

[[trusted.globset]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep-cli]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep-matcher]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep-pcre2]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep-printer]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep-regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.grep-searcher]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.ignore]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-15"
end = "2026-04-27"

[[trusted.jobserver]]
criteria = "safe-to-deploy"
user-id = 1
start = "2019-03-15"
end = "2026-04-27"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 51017
start = "2020-03-17"
end = "2026-04-27"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-04-27"

[[trusted.pcre2]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-14"
end = "2026-04-27"

[[trusted.pcre2-sys]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-14"
end = "2026-04-27"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2026-04-27"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2026-04-27"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2026-04-27"

[[trusted.ripgrep]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-16"
end = "2026-04-27"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-05-02"
end = "2026-04-27"

[[trusted.same-file]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-16"
end = "2026-04-27"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-02-28"
end = "2026-04-27"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-03-01"
end = "2026-04-27"

[[trusted.termcolor]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-04"
end = "2026-04-27"

[[trusted.walkdir]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2026-04-27"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2020-01-11"
end = "2026-04-27"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-15"
end = "2026-04-27"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-09"
end = "2026-04-27"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2026-04-27"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-05"
end = "2026-04-27"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-28"
end = "2026-04-27"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2024-04-02"
end = "2026-04-27"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-27"
end = "2026-04-27"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-28"
end = "2026-04-27"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2026-04-27"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-10-27"
end = "2026-04-27"
